name: system_accent_color_ios
description: iOS platform implementation of system_accent_color
version: 0.0.2
repository: https://github.com/EchoEllet/dart-packages/tree/main/packages/system_accent_color/system_accent_color_ios
issue_tracker: https://github.com/EchoEllet/dart-packages/issues/new?labels=p%3A%20system_accent_color
topics: [system-accent-color, os-integration, dynamic-color, theming]

environment:
  sdk: ^3.10.0
  flutter: ">=3.38.0"

dependencies:
  system_accent_color_platform_interface: ^0.0.1

flutter:
  plugin:
    implements: system_accent_color
    platforms:
      ios:
        dartPluginClass: SystemAccentColorIOS
        fileName: system_accent_color_ios.dart
