name: api_client
description: "Enforces explicit failure handling for API calls."
version: 0.0.1
repository: https://github.com/EchoEllet/dart-packages/tree/main/packages/api_client
issue_tracker: https://github.com/EchoEllet/dart-packages/issues/new?labels=p%3A%20api_client
topics: [http, network, api, client]

environment:
  sdk: ^3.12.0

dependencies:
  http: ^1.4.0
  http_method_enum: ^0.0.1
  meta: ^1.16.0
  json_safe: ^0.0.1

dev_dependencies:
  test: ^1.24.0
  mocktail: ^1.0.4
