name: is_ios_simulator
description: Checks whether the app is running in the iOS Simulator or on a physical device
version: 1.0.1
repository: https://github.com/EchoEllet/dart-packages/tree/main/packages/is_ios_simulator
issue_tracker: https://github.com/EchoEllet/dart-packages/issues/new?labels=p%3A%20is_ios_simulator
topics: [ios, simulator, device]

environment:
  sdk: ^3.10.0
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  pigeon: ^27.3.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: IosSimulatorDetectionPlugin
