name: example
description: "Demonstrates how to use the flutter_secure_storage_linux_secret_service."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  material_ui: ^1.2.0
  flutter_secure_storage: ^11.1.0
  flutter_secure_storage_linux_secret_service:
    path: ../

flutter:
  uses-material-design: true
