// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;
import 'package:objective_c/objective_c.dart' as objc;
import 'package:ffi/ffi.dart' as pkg_ffi;

@ffi.Native<
  ffi.Pointer<objc.ObjCObjectImpl> Function(
    ffi.Pointer<objc.ObjCObjectImpl>,
    ffi.Pointer<ffi.Void>,
  )
>()
// ignore: unused_element
external ffi.Pointer<objc.ObjCObjectImpl> _AppKitFFI_protocolTrampoline_1mbt9g9(
  ffi.Pointer<objc.ObjCObjectImpl> target,
  ffi.Pointer<ffi.Void> arg0,
);

enum NSCompositingOperation {
  NSCompositingOperationClear(0),
  NSCompositingOperationCopy(1),
  NSCompositingOperationSourceOver(2),
  NSCompositingOperationSourceIn(3),
  NSCompositingOperationSourceOut(4),
  NSCompositingOperationSourceAtop(5),
  NSCompositingOperationDestinationOver(6),
  NSCompositingOperationDestinationIn(7),
  NSCompositingOperationDestinationOut(8),
  NSCompositingOperationDestinationAtop(9),
  NSCompositingOperationXOR(10),
  NSCompositingOperationPlusDarker(11),
  NSCompositingOperationHighlight(12),
  NSCompositingOperationPlusLighter(13),
  NSCompositingOperationMultiply(14),
  NSCompositingOperationScreen(15),
  NSCompositingOperationOverlay(16),
  NSCompositingOperationDarken(17),
  NSCompositingOperationLighten(18),
  NSCompositingOperationColorDodge(19),
  NSCompositingOperationColorBurn(20),
  NSCompositingOperationSoftLight(21),
  NSCompositingOperationHardLight(22),
  NSCompositingOperationDifference(23),
  NSCompositingOperationExclusion(24),
  NSCompositingOperationHue(25),
  NSCompositingOperationSaturation(26),
  NSCompositingOperationColor(27),
  NSCompositingOperationLuminosity(28);

  final int value;
  const NSCompositingOperation(this.value);

  static NSCompositingOperation fromValue(int value) => switch (value) {
    0 => NSCompositingOperationClear,
    1 => NSCompositingOperationCopy,
    2 => NSCompositingOperationSourceOver,
    3 => NSCompositingOperationSourceIn,
    4 => NSCompositingOperationSourceOut,
    5 => NSCompositingOperationSourceAtop,
    6 => NSCompositingOperationDestinationOver,
    7 => NSCompositingOperationDestinationIn,
    8 => NSCompositingOperationDestinationOut,
    9 => NSCompositingOperationDestinationAtop,
    10 => NSCompositingOperationXOR,
    11 => NSCompositingOperationPlusDarker,
    12 => NSCompositingOperationHighlight,
    13 => NSCompositingOperationPlusLighter,
    14 => NSCompositingOperationMultiply,
    15 => NSCompositingOperationScreen,
    16 => NSCompositingOperationOverlay,
    17 => NSCompositingOperationDarken,
    18 => NSCompositingOperationLighten,
    19 => NSCompositingOperationColorDodge,
    20 => NSCompositingOperationColorBurn,
    21 => NSCompositingOperationSoftLight,
    22 => NSCompositingOperationHardLight,
    23 => NSCompositingOperationDifference,
    24 => NSCompositingOperationExclusion,
    25 => NSCompositingOperationHue,
    26 => NSCompositingOperationSaturation,
    27 => NSCompositingOperationColor,
    28 => NSCompositingOperationLuminosity,
    _ => throw ArgumentError(
      'Unknown value for NSCompositingOperation: $value',
    ),
  };
}

sealed class NSPasteboardWritingOptions {
  static const NSPasteboardWritingPromised = 512;
}

/// WARNING: NSPasteboardWriting is a stub. To generate bindings for this class, include
/// NSPasteboardWriting in your config's objc-protocols list.
///
/// NSPasteboardWriting
extension type NSPasteboardWriting._(objc.ObjCProtocol object$)
    implements objc.ObjCProtocol, objc.NSObjectProtocol {
  /// Constructs a [NSPasteboardWriting] that points to the same underlying object as [other].
  NSPasteboardWriting.as(objc.ObjCObject other) : object$ = other;

  /// Constructs a [NSPasteboardWriting] that wraps the given raw object pointer.
  NSPasteboardWriting.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCProtocol(other, retain: retain, release: release);
}

/// WARNING: NSPasteboardReading is a stub. To generate bindings for this class, include
/// NSPasteboardReading in your config's objc-protocols list.
///
/// NSPasteboardReading
extension type NSPasteboardReading._(objc.ObjCProtocol object$)
    implements objc.ObjCProtocol, objc.NSObjectProtocol {
  /// Constructs a [NSPasteboardReading] that points to the same underlying object as [other].
  NSPasteboardReading.as(objc.ObjCObject other) : object$ = other;

  /// Constructs a [NSPasteboardReading] that wraps the given raw object pointer.
  NSPasteboardReading.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCProtocol(other, retain: retain, release: release);
}

/// WARNING: CIColor is a stub. To generate bindings for this class, include
/// CIColor in your config's objc-interfaces list.
///
/// CIColor
extension type CIColor._(objc.ObjCObject object$)
    implements
        objc.ObjCObject,
        objc.NSObject,
        objc.NSSecureCoding,
        objc.NSCopying {
  /// Constructs a [CIColor] that points to the same underlying object as [other].
  CIColor.as(objc.ObjCObject other) : object$ = other {
    objc.checkOsVersionInternal('CIColor', macOS: (false, (10, 4, 0)));
  }

  /// Constructs a [CIColor] that wraps the given raw object pointer.
  CIColor.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCObject(other, retain: retain, release: release) {
    objc.checkOsVersionInternal('CIColor', macOS: (false, (10, 4, 0)));
  }
}

late final _class_NSColor = objc.getClass("NSColor");
late final _sel_isKindOfClass_ = objc.registerName("isKindOfClass:");
final _objc_msgSend_19nvye5 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Bool Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >
    >()
    .asFunction<
      bool Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
      )
    >();
late final _class_NSColorSpace = objc.getClass("NSColorSpace");
late final _sel_deviceRGBColorSpace = objc.registerName("deviceRGBColorSpace");
final _objc_msgSend_151sglz = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Pointer<objc.ObjCObjectImpl> Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      ffi.Pointer<objc.ObjCObjectImpl> Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();

/// NSColorSpace
extension type NSColorSpace._(objc.ObjCObject object$)
    implements objc.ObjCObject, objc.NSObject, objc.NSSecureCoding {
  /// Constructs a [NSColorSpace] that points to the same underlying object as [other].
  NSColorSpace.as(objc.ObjCObject other) : object$ = other {
    objc.checkOsVersionInternal('NSColorSpace', iOS: (true, null));
    assert(isA(object$));
  }

  /// Constructs a [NSColorSpace] that wraps the given raw object pointer.
  NSColorSpace.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCObject(other, retain: retain, release: release) {
    objc.checkOsVersionInternal('NSColorSpace', iOS: (true, null));
    assert(isA(object$));
  }

  /// Returns whether [obj] is an instance of [NSColorSpace].
  static bool isA(objc.ObjCObject obj) => _objc_msgSend_19nvye5(
    obj.ref.pointer,
    _sel_isKindOfClass_,
    _class_NSColorSpace,
  );

  /// deviceRGBColorSpace
  static NSColorSpace getDeviceRGBColorSpace() {
    objc.checkOsVersionInternal(
      'NSColorSpace.deviceRGBColorSpace',
      iOS: (true, null),
    );
    final $ret = _objc_msgSend_151sglz(
      _class_NSColorSpace,
      _sel_deviceRGBColorSpace,
    );
    return NSColorSpace.fromPointer($ret, retain: true, release: true);
  }
}

extension NSColorSpace$Methods on NSColorSpace {}

late final _sel_colorUsingColorSpace_ = objc.registerName(
  "colorUsingColorSpace:",
);
final _objc_msgSend_1sotr3r = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Pointer<objc.ObjCObjectImpl> Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >
    >()
    .asFunction<
      ffi.Pointer<objc.ObjCObjectImpl> Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
      )
    >();
late final _sel_controlAccentColor = objc.registerName("controlAccentColor");
late final _sel_redComponent = objc.registerName("redComponent");
final _objc_msgSend_1ukqyt8 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Double Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      double Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
final _objc_msgSend_1ukqyt8Fpret = objc.msgSendFpretPointer
    .cast<
      ffi.NativeFunction<
        ffi.Double Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      double Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
late final _sel_greenComponent = objc.registerName("greenComponent");
late final _sel_blueComponent = objc.registerName("blueComponent");
late final _sel_alphaComponent = objc.registerName("alphaComponent");
late final _sel_controlHighlightColor = objc.registerName(
  "controlHighlightColor",
);
late final _sel_controlLightHighlightColor = objc.registerName(
  "controlLightHighlightColor",
);
late final _sel_controlShadowColor = objc.registerName("controlShadowColor");
late final _sel_controlDarkShadowColor = objc.registerName(
  "controlDarkShadowColor",
);
late final _sel_scrollBarColor = objc.registerName("scrollBarColor");
late final _sel_knobColor = objc.registerName("knobColor");
late final _sel_selectedKnobColor = objc.registerName("selectedKnobColor");
late final _sel_windowFrameColor = objc.registerName("windowFrameColor");
late final _sel_selectedMenuItemColor = objc.registerName(
  "selectedMenuItemColor",
);
late final _sel_headerColor = objc.registerName("headerColor");
late final _sel_secondarySelectedControlColor = objc.registerName(
  "secondarySelectedControlColor",
);
late final _sel_alternateSelectedControlColor = objc.registerName(
  "alternateSelectedControlColor",
);
late final _sel_controlAlternatingRowBackgroundColors = objc.registerName(
  "controlAlternatingRowBackgroundColors",
);
late final _sel_colorSpaceName = objc.registerName("colorSpaceName");
late final _sel_colorUsingColorSpaceName_device_ = objc.registerName(
  "colorUsingColorSpaceName:device:",
);
final _objc_msgSend_15qeuct = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Pointer<objc.ObjCObjectImpl> Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >
    >()
    .asFunction<
      ffi.Pointer<objc.ObjCObjectImpl> Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCObjectImpl>,
      )
    >();
late final _sel_colorUsingColorSpaceName_ = objc.registerName(
  "colorUsingColorSpaceName:",
);

/// NSDeprecated
extension NSDeprecated on NSColor {
  /// colorSpaceName
  objc.NSString get colorSpaceName {
    objc.checkOsVersionInternal(
      'NSColor.colorSpaceName',
      iOS: (true, null),
      macOS: (false, (10, 0, 0)),
    );
    final $ret = _objc_msgSend_151sglz(
      object$.ref.pointer,
      _sel_colorSpaceName,
    );
    return objc.NSString.fromPointer($ret, retain: true, release: true);
  }

  /// colorUsingColorSpaceName:
  NSColor? colorUsingColorSpaceName(objc.NSString name) {
    objc.checkOsVersionInternal(
      'NSColor.colorUsingColorSpaceName:',
      iOS: (true, null),
      macOS: (false, (10, 0, 0)),
    );
    final $ret = _objc_msgSend_1sotr3r(
      object$.ref.pointer,
      _sel_colorUsingColorSpaceName_,
      name.ref.pointer,
    );
    return $ret.address == 0
        ? null
        : NSColor.fromPointer($ret, retain: true, release: true);
  }

  /// colorUsingColorSpaceName:device:
  NSColor? colorUsingColorSpaceName$1(
    objc.NSString? name, {
    objc.NSDictionary? device,
  }) {
    objc.checkOsVersionInternal(
      'NSColor.colorUsingColorSpaceName:device:',
      iOS: (true, null),
      macOS: (false, (10, 0, 0)),
    );
    final $ret = _objc_msgSend_15qeuct(
      object$.ref.pointer,
      _sel_colorUsingColorSpaceName_device_,
      name?.ref.pointer ?? ffi.nullptr,
      device?.ref.pointer ?? ffi.nullptr,
    );
    return $ret.address == 0
        ? null
        : NSColor.fromPointer($ret, retain: true, release: true);
  }

  /// alternateSelectedControlColor
  static NSColor getAlternateSelectedControlColor() {
    objc.checkOsVersionInternal(
      'NSColor.alternateSelectedControlColor',
      iOS: (true, null),
      macOS: (false, (10, 2, 0)),
    );
    final $ret = _objc_msgSend_151sglz(
      _class_NSColor,
      _sel_alternateSelectedControlColor,
    );
    return NSColor.fromPointer($ret, retain: true, release: true);
  }

  /// controlAlternatingRowBackgroundColors
  static objc.NSArray getControlAlternatingRowBackgroundColors() {
    objc.checkOsVersionInternal(
      'NSColor.controlAlternatingRowBackgroundColors',
      iOS: (true, null),
      macOS: (false, (10, 3, 0)),
    );
    final $ret = _objc_msgSend_151sglz(
      _class_NSColor,
      _sel_controlAlternatingRowBackgroundColors,
    );
    return objc.NSArray.fromPointer($ret, retain: true, release: true);
  }

  /// controlDarkShadowColor
  static NSColor getControlDarkShadowColor() {
    objc.checkOsVersionInternal(
      'NSColor.controlDarkShadowColor',
      iOS: (true, null),
      macOS: (false, (10, 0, 0)),
    );
    final $ret = _objc_msgSend_151sglz(
      _class_NSColor,
      _sel_controlDarkShadowColor,
    );
    return NSColor.fromPointer($ret, retain: true, release: true);
  }

  /// controlHighlightColor
  static NSColor getControlHighlightColor() {
    objc.checkOsVersionInternal(
      'NSColor.controlHighlightColor',
      iOS: (true, null),
      macOS: (false, (10, 0, 0)),
    );
    final $ret = _objc_msgSend_151sglz(
      _class_NSColor,
      _sel_controlHighlightColor,
    );
    return NSColor.fromPointer($ret, retain: true, release: true);
  }

  /// controlLightHighlightColor
  static NSColor getControlLightHighlightColor() {
    objc.checkOsVersionInternal(
      'NSColor.controlLightHighlightColor',
      iOS: (true, null),
      macOS: (false, (10, 0, 0)),
    );
    final $ret = _objc_msgSend_151sglz(
      _class_NSColor,
      _sel_controlLightHighlightColor,
    );
    return NSColor.fromPointer($ret, retain: true, release: true);
  }

  /// controlShadowColor
  static NSColor getControlShadowColor() {
    objc.checkOsVersionInternal(
      'NSColor.controlShadowColor',
      iOS: (true, null),
      macOS: (false, (10, 0, 0)),
    );
    final $ret = _objc_msgSend_151sglz(_class_NSColor, _sel_controlShadowColor);
    return NSColor.fromPointer($ret, retain: true, release: true);
  }

  /// headerColor
  static NSColor getHeaderColor() {
    objc.checkOsVersionInternal(
      'NSColor.headerColor',
      iOS: (true, null),
      macOS: (false, (10, 0, 0)),
    );
    final $ret = _objc_msgSend_151sglz(_class_NSColor, _sel_headerColor);
    return NSColor.fromPointer($ret, retain: true, release: true);
  }

  /// knobColor
  static NSColor getKnobColor() {
    objc.checkOsVersionInternal(
      'NSColor.knobColor',
      iOS: (true, null),
      macOS: (false, (10, 0, 0)),
    );
    final $ret = _objc_msgSend_151sglz(_class_NSColor, _sel_knobColor);
    return NSColor.fromPointer($ret, retain: true, release: true);
  }

  /// scrollBarColor
  static NSColor getScrollBarColor() {
    objc.checkOsVersionInternal(
      'NSColor.scrollBarColor',
      iOS: (true, null),
      macOS: (false, (10, 0, 0)),
    );
    final $ret = _objc_msgSend_151sglz(_class_NSColor, _sel_scrollBarColor);
    return NSColor.fromPointer($ret, retain: true, release: true);
  }

  /// secondarySelectedControlColor
  static NSColor getSecondarySelectedControlColor() {
    objc.checkOsVersionInternal(
      'NSColor.secondarySelectedControlColor',
      iOS: (true, null),
      macOS: (false, (10, 1, 0)),
    );
    final $ret = _objc_msgSend_151sglz(
      _class_NSColor,
      _sel_secondarySelectedControlColor,
    );
    return NSColor.fromPointer($ret, retain: true, release: true);
  }

  /// selectedKnobColor
  static NSColor getSelectedKnobColor() {
    objc.checkOsVersionInternal(
      'NSColor.selectedKnobColor',
      iOS: (true, null),
      macOS: (false, (10, 0, 0)),
    );
    final $ret = _objc_msgSend_151sglz(_class_NSColor, _sel_selectedKnobColor);
    return NSColor.fromPointer($ret, retain: true, release: true);
  }

  /// selectedMenuItemColor
  static NSColor getSelectedMenuItemColor() {
    objc.checkOsVersionInternal(
      'NSColor.selectedMenuItemColor',
      iOS: (true, null),
      macOS: (false, (10, 0, 0)),
    );
    final $ret = _objc_msgSend_151sglz(
      _class_NSColor,
      _sel_selectedMenuItemColor,
    );
    return NSColor.fromPointer($ret, retain: true, release: true);
  }

  /// windowFrameColor
  static NSColor getWindowFrameColor() {
    objc.checkOsVersionInternal(
      'NSColor.windowFrameColor',
      iOS: (true, null),
      macOS: (false, (10, 0, 0)),
    );
    final $ret = _objc_msgSend_151sglz(_class_NSColor, _sel_windowFrameColor);
    return NSColor.fromPointer($ret, retain: true, release: true);
  }
}

late final _sel_colorWithCIColor_ = objc.registerName("colorWithCIColor:");

/// NSQuartzCoreAdditions
extension NSQuartzCoreAdditions on NSColor {
  /// colorWithCIColor:
  static NSColor colorWithCIColor(CIColor color) {
    objc.checkOsVersionInternal('NSColor.colorWithCIColor:', iOS: (true, null));
    final $ret = _objc_msgSend_1sotr3r(
      _class_NSColor,
      _sel_colorWithCIColor_,
      color.ref.pointer,
    );
    return NSColor.fromPointer($ret, retain: true, release: true);
  }
}

late final _sel_accessibilityName = objc.registerName("accessibilityName");

/// Construction methods for `objc.ObjCBlock<objc.NSString Function(ffi.Pointer<ffi.Void>)>`.
abstract final class ObjCBlock_NSString_ffiVoid {
  /// Returns a block that wraps the given raw block pointer.
  static objc.ObjCBlock<objc.NSString Function(ffi.Pointer<ffi.Void>)>
  fromPointer(
    ffi.Pointer<objc.ObjCBlockImpl> pointer, {
    bool retain = false,
    bool release = false,
  }) => objc.ObjCBlock<objc.NSString Function(ffi.Pointer<ffi.Void>)>(
    pointer,
    retain: retain,
    release: release,
  );

  /// Creates a block from a C function pointer.
  ///
  /// This block must be invoked by native code running on the same thread as
  /// the isolate that registered it. Invoking the block on the wrong thread
  /// will result in a crash.
  static objc.ObjCBlock<objc.NSString Function(ffi.Pointer<ffi.Void>)>
  fromFunctionPointer(
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Pointer<objc.ObjCObjectImpl> Function(ffi.Pointer<ffi.Void> arg0)
      >
    >
    ptr,
  ) => objc.ObjCBlock<objc.NSString Function(ffi.Pointer<ffi.Void>)>(
    objc.newPointerBlock(_fnPtrCallable, ptr.cast()),
    retain: false,
    release: true,
  );

  /// Creates a block from a Dart function.
  ///
  /// This block must be invoked by native code running on the same thread as
  /// the isolate that registered it. Invoking the block on the wrong thread
  /// will result in a crash.
  ///
  /// If `keepIsolateAlive` is true, this block will keep this isolate alive
  /// until it is garbage collected by both Dart and ObjC.
  static objc.ObjCBlock<objc.NSString Function(ffi.Pointer<ffi.Void>)>
  fromFunction(
    objc.NSString Function(ffi.Pointer<ffi.Void>) fn, {
    bool keepIsolateAlive = true,
  }) => objc.ObjCBlock<objc.NSString Function(ffi.Pointer<ffi.Void>)>(
    objc.newClosureBlock(
      _closureCallable,
      (ffi.Pointer<ffi.Void> arg0) => fn(arg0).ref.retainAndAutorelease(),
      keepIsolateAlive,
    ),
    retain: false,
    release: true,
  );

  static ffi.Pointer<objc.ObjCObjectImpl> _fnPtrTrampoline(
    ffi.Pointer<objc.ObjCBlockImpl> block,
    ffi.Pointer<ffi.Void> arg0,
  ) => block.ref.target
      .cast<
        ffi.NativeFunction<
          ffi.Pointer<objc.ObjCObjectImpl> Function(ffi.Pointer<ffi.Void> arg0)
        >
      >()
      .asFunction<
        ffi.Pointer<objc.ObjCObjectImpl> Function(ffi.Pointer<ffi.Void>)
      >()(arg0);
  static ffi.Pointer<ffi.Void> _fnPtrCallable =
      ffi.Pointer.fromFunction<
            ffi.Pointer<objc.ObjCObjectImpl> Function(
              ffi.Pointer<objc.ObjCBlockImpl>,
              ffi.Pointer<ffi.Void>,
            )
          >(_fnPtrTrampoline)
          .cast();
  static ffi.Pointer<objc.ObjCObjectImpl> _closureTrampoline(
    ffi.Pointer<objc.ObjCBlockImpl> block,
    ffi.Pointer<ffi.Void> arg0,
  ) =>
      (objc.getBlockClosure(block)
          as ffi.Pointer<objc.ObjCObjectImpl> Function(ffi.Pointer<ffi.Void>))(
        arg0,
      );
  static ffi.Pointer<ffi.Void> _closureCallable =
      ffi.Pointer.fromFunction<
            ffi.Pointer<objc.ObjCObjectImpl> Function(
              ffi.Pointer<objc.ObjCBlockImpl>,
              ffi.Pointer<ffi.Void>,
            )
          >(_closureTrampoline)
          .cast();
}

/// Call operator for `objc.ObjCBlock<objc.NSString Function(ffi.Pointer<ffi.Void>)>`.
extension ObjCBlock_NSString_ffiVoid$CallExtension
    on objc.ObjCBlock<objc.NSString Function(ffi.Pointer<ffi.Void>)> {
  objc.NSString call(ffi.Pointer<ffi.Void> arg0) => objc.NSString.fromPointer(
    ref.pointer.ref.invoke
        .cast<
          ffi.NativeFunction<
            ffi.Pointer<objc.ObjCObjectImpl> Function(
              ffi.Pointer<objc.ObjCBlockImpl> block,
              ffi.Pointer<ffi.Void> arg0,
            )
          >
        >()
        .asFunction<
          ffi.Pointer<objc.ObjCObjectImpl> Function(
            ffi.Pointer<objc.ObjCBlockImpl>,
            ffi.Pointer<ffi.Void>,
          )
        >()(ref.pointer, arg0),
    retain: true,
    release: true,
  );
}

/// WARNING: NSAccessibilityColor is a stub. To generate bindings for this class, include
/// NSAccessibilityColor in your config's objc-protocols list.
///
/// NSAccessibilityColor
extension type NSAccessibilityColor._(objc.ObjCProtocol object$)
    implements objc.ObjCProtocol {
  /// Constructs a [NSAccessibilityColor] that points to the same underlying object as [other].
  NSAccessibilityColor.as(objc.ObjCObject other) : object$ = other;

  /// Constructs a [NSAccessibilityColor] that wraps the given raw object pointer.
  NSAccessibilityColor.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCProtocol(other, retain: retain, release: release);
}

/// NSAccessibilityColorConformance
extension NSAccessibilityColorConformance on NSColor {
  /// accessibilityName
  objc.NSString get accessibilityName {
    objc.checkOsVersionInternal(
      'NSColor.accessibilityName',
      macOS: (false, (11, 0, 0)),
    );
    final $ret = _objc_msgSend_151sglz(
      object$.ref.pointer,
      _sel_accessibilityName,
    );
    return objc.NSString.fromPointer($ret, retain: true, release: true);
  }
}

/// NSColor
extension type NSColor._(objc.ObjCObject object$)
    implements
        objc.ObjCObject,
        objc.NSObject,
        objc.NSCopying,
        objc.NSSecureCoding,
        NSPasteboardReading,
        NSPasteboardWriting {
  /// Constructs a [NSColor] that points to the same underlying object as [other].
  NSColor.as(objc.ObjCObject other) : object$ = other {
    objc.checkOsVersionInternal('NSColor', iOS: (true, null));
    assert(isA(object$));
  }

  /// Constructs a [NSColor] that wraps the given raw object pointer.
  NSColor.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCObject(other, retain: retain, release: release) {
    objc.checkOsVersionInternal('NSColor', iOS: (true, null));
    assert(isA(object$));
  }

  /// Returns whether [obj] is an instance of [NSColor].
  static bool isA(objc.ObjCObject obj) => _objc_msgSend_19nvye5(
    obj.ref.pointer,
    _sel_isKindOfClass_,
    _class_NSColor,
  );

  /// controlAccentColor
  static NSColor getControlAccentColor() {
    objc.checkOsVersionInternal(
      'NSColor.controlAccentColor',
      iOS: (true, null),
      macOS: (false, (10, 14, 0)),
    );
    final $ret = _objc_msgSend_151sglz(_class_NSColor, _sel_controlAccentColor);
    return NSColor.fromPointer($ret, retain: true, release: true);
  }
}

extension NSColor$Methods on NSColor {
  /// alphaComponent
  double get alphaComponent {
    objc.checkOsVersionInternal('NSColor.alphaComponent', iOS: (true, null));
    return objc.useMsgSendVariants
        ? _objc_msgSend_1ukqyt8Fpret(object$.ref.pointer, _sel_alphaComponent)
        : _objc_msgSend_1ukqyt8(object$.ref.pointer, _sel_alphaComponent);
  }

  /// blueComponent
  double get blueComponent {
    objc.checkOsVersionInternal('NSColor.blueComponent', iOS: (true, null));
    return objc.useMsgSendVariants
        ? _objc_msgSend_1ukqyt8Fpret(object$.ref.pointer, _sel_blueComponent)
        : _objc_msgSend_1ukqyt8(object$.ref.pointer, _sel_blueComponent);
  }

  /// colorUsingColorSpace:
  NSColor? colorUsingColorSpace(NSColorSpace space) {
    objc.checkOsVersionInternal(
      'NSColor.colorUsingColorSpace:',
      iOS: (true, null),
    );
    final $ret = _objc_msgSend_1sotr3r(
      object$.ref.pointer,
      _sel_colorUsingColorSpace_,
      space.ref.pointer,
    );
    return $ret.address == 0
        ? null
        : NSColor.fromPointer($ret, retain: true, release: true);
  }

  /// greenComponent
  double get greenComponent {
    objc.checkOsVersionInternal('NSColor.greenComponent', iOS: (true, null));
    return objc.useMsgSendVariants
        ? _objc_msgSend_1ukqyt8Fpret(object$.ref.pointer, _sel_greenComponent)
        : _objc_msgSend_1ukqyt8(object$.ref.pointer, _sel_greenComponent);
  }

  /// redComponent
  double get redComponent {
    objc.checkOsVersionInternal('NSColor.redComponent', iOS: (true, null));
    return objc.useMsgSendVariants
        ? _objc_msgSend_1ukqyt8Fpret(object$.ref.pointer, _sel_redComponent)
        : _objc_msgSend_1ukqyt8(object$.ref.pointer, _sel_redComponent);
  }
}
