name: system_accent_color_windows
description: Windows platform implementation of system_accent_color
version: 0.0.2
repository: https://github.com/EchoEllet/dart-packages/tree/main/packages/system_accent_color/system_accent_color_windows
issue_tracker: https://github.com/EchoEllet/dart-packages/issues/new?labels=p%3A%20system_accent_color
topics: [system-accent-color, os-integration, dynamic-color, theming]

environment:
  sdk: ^3.10.0
  flutter: ">=3.38.0"

dependencies:
  ffi: ^2.2.0
  system_accent_color_platform_interface: ^0.0.1
  win32: ^6.3.0

flutter:
  plugin:
    implements: system_accent_color
    platforms:
      windows:
        dartPluginClass: SystemAccentColorWindows
        fileName: system_accent_color_windows.dart
