name: example
description: "Demonstrates how to use the system_accent_color."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  system_accent_color:
    path: ../

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
