import 'package:api_client/src/http_response.dart';
import 'package:api_client/src/http_status_result.dart';
import 'package:api_client/src/multipart/multipart_body.dart'
    show MultipartBody;
import 'package:api_client/src/request_body.dart';
import 'package:http/http.dart' as http show MultipartFile;
import 'package:http_method_enum/http_method_enum.dart';
import 'package:json_safe/json_safe.dart' show JsonMap, JsonParseException;

export 'package:http_method_enum/http_method_enum.dart' show HttpMethod;
export 'package:json_safe/json_safe.dart'
    show
        JsonDecodingException,
        JsonDeserializationException,
        JsonObjectExpectedException,
        JsonParseException;

/// An HTTP client for APIs that return responses using the [Result] pattern.
///
/// Provides the following on top of a standard HTTP client:
///
/// * Wraps all responses in a [Result], enforce handling transport-level issues.
///
/// * When using [requestJson], automatically adds the `Accept: application/json` header,
///   and expects responses to be always JSON.
///
/// * For all HTTP methods where [HttpMethod.supportsRequestBody] is `true`:
///
///   - Optionally encodes the request body as JSON and sets the
///     `Content-Type: application/json` header when sending a JSON body,
///     by passing a [JsonRequestBody] to [body] argument when calling either [request]
///     or [requestJson].
///
///   - Supports a multipart request body and sets the
///     `Content-Type: multipart/form-data; boundary=$boundary` header,
///     with the boundary automatically generated by the HTTP client implementation,
///     by passing a [MultipartBody] to [body] argument when calling either [request]
///     or [requestJson].
///
/// Example:
///
/// ```dart
/// final HttpApiClient client = HttpApiClientDart(...);
///
/// final result = await client.requestJson<Example, String>(
///   Uri.https('api.example.com'),
///   method: HttpMethod.post,
///   body: RequestBody.json({'example': 'JSON'}),
///   deserializeSuccess: (response) => Example.fromJson(response.body),
///   deserializeError: (response) => response.body['error_code']! as String,
/// );
/// ```
///
/// This client interface applies specific design decisions:
///
/// * Applies only to [requestJson]:
///   Requires JSON format for all successful and error responses.
///   If the API does not always return JSON, use [request]
///   instead for more control.
///
/// * The class [http.MultipartFile] from `package:http` is part of this API for
///   performance, simplicity, testability, and separation of concerns reasons.
///
///   This makes removing the `package:http` dependency slightly harder.
///   However, that does not enforce the `http` client implementation (by dart.dev).
///   For more info, visit the file that exports [http.MultipartFile] which is
///   the same file that defines [MultipartBody].
///
/// * Does not support lazy streaming of request or response bodies,
///   as API clients typically do not require it. Responses are always
///   returned as a raw [String] with [request], or as a decoded class
///   with [requestJson] rather than raw bytes.
abstract interface class HttpApiClient {
  /// Sends an HTTP request and deserializes the JSON response.
  ///
  /// Unlike [request], this automatically adds the `Accept: application/json` header
  /// and expects all responses to be valid JSON.
  ///
  /// If the API returns inconsistent responses (e.g., sometimes JSON, sometimes empty or non-JSON),
  /// use [request] instead for more control.
  ///
  /// Use [deserializeSuccess] and [deserializeError] to parse the response body.
  /// Both receive the [HttpResponse] with the decoded JSON as a [JsonMap],
  /// suitable for passing to `fromJson`.
  ///
  /// - [deserializeSuccess] is used for 2xx responses.
  /// - [deserializeError] is used for non-2xx responses (e.g., 4xx, 5xx).
  ///
  /// Throws [JsonParseException] if the response body:
  ///
  /// - is invalid or malformed JSON
  /// - does not match the expected model structure or types
  ///   - when either [deserializeSuccess] or [deserializeError] throws a [TypeError] (`json_serializable` generates code that throws this Dart error)
  ///
  /// {@macro requestCommon}
  Future<HttpStatusResult<S, E>> requestJson<S, E>(
    Uri url, {
    required HttpMethod method,
    Map<String, String>? headers,
    RequestBody? body,
    required JsonResponseDeserializer<S> deserializeSuccess,
    required JsonResponseDeserializer<E> deserializeError,
  });

  /// Sends an HTTP request. For JSON support, consider [requestJson].
  ///
  /// {@template requestCommon}
  ///
  /// Throws an [ArgumentError] if [body] is non-null and [method] does not
  /// support a request body (i.e., [HttpMethod.supportsRequestBody] is `false`),
  /// since such HTTP methods must not have a body.
  ///
  /// See also: [RequestBody]
  ///
  /// {@endtemplate}
  Future<HttpStatusResult<String, String>> request(
    Uri url, {
    required HttpMethod method,
    Map<String, String>? headers,
    RequestBody? body,
  });
}

typedef JsonResponseDeserializer<T> = T Function(JsonHttpResponse response);
