name: xdg_secret_portal_store_default
description: A default cryptographic implementation of xdg_secret_portal_store that uses package:cryptography
version: 0.1.1
repository: https://github.com/EchoEllet/dart-packages/tree/main/packages/linux_secret_store/xdg_secret_portal_store_default
issue_tracker: https://github.com/EchoEllet/dart-packages/issues/new?labels=p%3A%20xdg_secret_portal_store_default
topics: [os-integration, xdg-portal, secure-storage]

environment:
  sdk: ^3.10.0

dependencies:
  cryptography: ^2.9.0
  xdg_secret_portal_store: ^0.1.0

dev_dependencies:
  test: ^1.25.6
